services:
  app:
    build: .
    container_name: neoblog-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      APP_ENV: development
      APP_TIMEZONE: Africa/Lagos
      DB_DRIVER: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: php_blog
      DB_USER: blog
      DB_PASS: blog
    volumes:
      - ./:/var/www/html
      - uploads:/var/www/html/public/uploads

  db:
    image: mysql:8.0
    container_name: neoblog-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      php_blog
      MYSQL_USER:          blog
      MYSQL_PASSWORD:      blog
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/schema.mysql.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout:  5s
      retries:  20

volumes:
  dbdata:
  uploads:
